---
- name: Wait for port 22 to become open on the host, don't start checking for 120 seconds
  hosts: all
  gather_facts: False
  tasks:
  - name: Open 22 port
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      search_regex: OpenSSH
      delay: 30
      timeout: 300
    vars:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3


- name: Instaling Docker-deamon & python for server
  hosts: all
  become: yes
  become_user: ec2-user
  tasks:
  - name: Install the latest version python
    vars:
      ansible_python_interpreter: /usr/bin/python2
    yum:
     name:  python3.*
     update_cache: yes
     state: present

- name: Install latest version of docker & nginx
  hosts: all
  become: yes
  become_user: root
  tasks:
  - name: Install docker & pip
    yum:
     name:
      - docker
      - python-pip
      - python2-pip
     update_cache: yes 
     state: present
  
  - name: Install nginx
    yum: 
      name:
        - nginx
        - net-tools
        - unzip
      state: latest
      update_cache: true

    
- name: start Docker for server
  hosts: all
  become: yes
  tasks:
  - name: start Docker
    systemd: 
      name: docker
      state: started
  - name: Start Nginx
    systemd:
      name: nginx
      state: started

- name: Install docker for python from pip
  hosts: all
  become: yes
  become_user: ec2-user
  tasks:
  - name: Install docker python3 module
    pip:
      name: docker
          
- name: Adding ec2-user to docker
  hosts: all
  become: yes
  tasks:
  - name: add ec2-user to docker-group
    user: 
      name: ec2-user
      groups: docker
      append: yes

  - name: Reconect session
    meta: reset_connection 

- name: Copy docker-tar & script file to remote
  hosts: all
  become: true
  tasks:
  - name: Copy tar to remote
    copy:
     src: "directory_path_of_src_code"
     dest: /home/ec2-user/

  - name:  unarchive file
    unarchive: 
     src: /home/ec2-user/"file-name"
     dest: /home/ec2-user/
     remote_src: yes

  - name: Change file ownership, group and permissions
    file:
     path: /home/ec2-user/"Directory_name"/
     owner: ec2-user
     group: ec2-user
     mode: '755'
  
  - name: Copy nginx conf file
    copy:
     src: ./ansible/my-demo.conf
     dest: /etc/nginx/conf.d
     
- name: Build & run docker
  hosts: all
  become: ec2-user
  tasks:   
  - name: build container image
    docker_image:
      name: my-demo
      build:
        path: /home/ec2-user/"directory_name"/
      source: build
 
- name: run docker
  hosts: all
  become: true
  become_user: root
  tasks: 
  - name: run the docker image
    command: docker run -d -p 3500:3500 my-demo
    args:
      chdir: /home/ec2-user/
  
- name: Restart Nginx server 
  hosts: all
  become: true
  tasks:
  - name: restart nginx
    service: 
      name: nginx
      state: restarted